server:
  port: 8080

eureka:
 instance:
   nonSecurePort: ${SCD_INSTANCE_PORT}
spring:
  cloud:
      config:
        server:
          git:
            uri: https://github.com/codersparks/springclouddocker-config.git