server:
  port: 8080

eureka:
 instance:
   preferIpAddress: true
spring:
  cloud:
      config:
        server:
          git:
            uri: https://github.com/codersparks/springclouddocker-config.git