server:
  port: 8888

spring:
  cloud:
      config:
        server:
          git:
            uri: https://github.com/codersparks/springclouddocker-config.git
eureka:
  instance:
      ip: ${SCD_DISCOVERY_INSTANCE_HOST}
      port: ${SCD_DISCOVERY_INSTANCE_PORT}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka/